### ISSUE TITLE
Few features are missing

### ISSUE THREAD

**Issue by pkgvrpdm** [Rahulghuge94/trade#2]
I am a trader and trade with Finvasia.
I would lie to join you and help in completing the missing features in your library like modify trade, cancel trade, BO, CO etc.
Your project is great idea and can provide free and easy way to auto trade on different platform.

Can you please provide me shoonya api and next features to add so that I can help develop those if you don't have time for that.

**Comment by Rahulghuge94** [comment]
hi, yeah sure. but i dont want to make available to everyone. so unnecessary brokers will make changes to their api. so i have to change all the codes again to get connect to the server. may be this time they encrypt the data like navia broker. but if you like contribute i will give you access.
